// This source code was generated by regenerator
module imgui.imgui_impl_win32;
extern(C++) {
extern(C++) bool ImGui_ImplWin32_Init(void* hwnd);
extern(C++) void ImGui_ImplWin32_Shutdown();
extern(C++) void ImGui_ImplWin32_NewFrame();
} // 
