// This source code was generated by regenerator
module windowskits.dcommon;
import windowskits.minwindef;
import core.sys.windows.windef;
import core.sys.windows.winnt;
import windowskits.dxgiformat;
import core.sys.windows.basetsd;
import windowskits.windef;
struct D2D_MATRIX_3X2_F___anonymous_6
{
    FLOAT m11;
    FLOAT m12;
    FLOAT m21;
    FLOAT m22;
    FLOAT dx;
    FLOAT dy;
}
struct D2D_MATRIX_3X2_F___anonymous_7
{
    FLOAT _11;
    FLOAT _12;
    FLOAT _21;
    FLOAT _22;
    FLOAT _31;
    FLOAT _32;
}
struct D2D_MATRIX_4X4_F___anonymous_27
{
    FLOAT _11;
    FLOAT _12;
    FLOAT _13;
    FLOAT _14;
    FLOAT _21;
    FLOAT _22;
    FLOAT _23;
    FLOAT _24;
    FLOAT _31;
    FLOAT _32;
    FLOAT _33;
    FLOAT _34;
    FLOAT _41;
    FLOAT _42;
    FLOAT _43;
    FLOAT _44;
}
struct D2D_RECT_F
{
    FLOAT left;
    FLOAT top;
    FLOAT right;
    FLOAT bottom;
}
struct D2D_MATRIX_3X2_F
{
    union {
        D2D_MATRIX_3X2_F___anonymous_6 __param__6;
        D2D_MATRIX_3X2_F___anonymous_7 __param__7;
        FLOAT[2][3] m;
    }
}
struct D2D_POINT_2F
{
    FLOAT x;
    FLOAT y;
}
struct D2D_SIZE_F
{
    FLOAT width;
    FLOAT height;
}
struct D2D1_PIXEL_FORMAT
{
    DXGI_FORMAT format;
    D2D1_ALPHA_MODE alphaMode;
}
enum D2D1_ALPHA_MODE
{
    _UNKNOWN = 0x0,
    _PREMULTIPLIED = 0x1,
    _STRAIGHT = 0x2,
    _IGNORE = 0x3,
    _FORCE_DWORD = 0xffffffff,
}
struct D2D_SIZE_U
{
    UINT32 width;
    UINT32 height;
}
struct D2D_POINT_2U
{
    UINT32 x;
    UINT32 y;
}
struct D2D_RECT_U
{
    UINT32 left;
    UINT32 top;
    UINT32 right;
    UINT32 bottom;
}
enum DWRITE_MEASURING_MODE
{
    _NATURAL = 0x0,
    _GDI_CLASSIC = 0x1,
    _GDI_NATURAL = 0x2,
}
struct D2D_MATRIX_4X4_F
{
    union {
        D2D_MATRIX_4X4_F___anonymous_27 __param__8;
        FLOAT[4][4] m;
    }
}
alias D2D_POINT_2L = POINT;
alias D2D_RECT_L = RECT;
