// This source code was generated by regenerator
module windowskits.documenttarget;
import core.sys.windows.unknwn;
import windowskits.guidutil;
import windowskits.intsafe;
import core.sys.windows.windef;
import core.sys.windows.basetyps;
import windowskits.oaidl;
import windowskits.winnt;
import core.sys.windows.winnt;
import windowskits.objidlbase;
interface IPrintDocumentPackageTarget: IUnknown
{
    static const iidof = parseGUID("1b8efec4-3019-4c27-964e-367202156906");
    HRESULT GetPackageTargetTypes(UINT32* targetCount, GUID** targetTypes);
    HRESULT GetPackageTarget(ref GUID guidTargetType, ref IID riid, void** ppvTarget);
    HRESULT Cancel();
}
interface IPrintDocumentPackageStatusEvent: IDispatch
{
    static const iidof = parseGUID("ed90c8ad-5c34-4d05-a1ec-0e8a9b3ad7af");
    HRESULT PackageStatusUpdated(PrintDocumentPackageStatus* packageStatus);
}
alias PrintDocumentPackageStatus = __MIDL___MIDL_itf_documenttarget_0000_0001_0001;
struct __MIDL___MIDL_itf_documenttarget_0000_0001_0001
{
    UINT32 JobId;
    INT32 CurrentDocument;
    INT32 CurrentPage;
    INT32 CurrentPageTotal;
    PrintDocumentPackageCompletion Completion;
    HRESULT PackageStatus;
}
enum PrintDocumentPackageCompletion
{
    _InProgress = 0x0,
    _Completed = 0x1,
    _Canceled = 0x2,
    _Failed = 0x3,
}
interface IPrintDocumentPackageTargetFactory: IUnknown
{
    static const iidof = parseGUID("d2959bf7-b31b-4a3d-9600-712eb1335ba4");
    HRESULT CreateDocumentPackageTargetForPrintJob(LPCWSTR printerName, LPCWSTR jobName, IStream jobOutputStream, IStream jobPrintTicketStream, IPrintDocumentPackageTarget* docPackageTarget);
}
