// This source code was generated by regenerator
module windowskits.guiddef;
import core.sys.windows.basetyps;
struct _GUID
{
    uint Data1;
    ushort Data2;
    ushort Data3;
    ubyte[8] Data4;
}
