// This source code was generated by regenerator
module windowskits.intsafe;
import core.sys.windows.windef;
alias UINT32 = uint;
alias UINT64 = ulong;
alias UINT16 = ushort;
alias INT16 = short;
alias INT32 = int;
alias ULONG_PTR = ulong;
alias UINT8 = ubyte;
