// This source code was generated by regenerator
module windowskits.minwindef;
import core.sys.windows.windef;
import core.sys.windows.winnt;
alias FILETIME = _FILETIME;
struct _FILETIME
{
    DWORD dwLowDateTime;
    DWORD dwHighDateTime;
}
