// This source code was generated by regenerator
module windowskits.minwinbase;
import core.sys.windows.winnt;
import windowskits.minwindef;
import core.sys.windows.windef;
struct _SECURITY_ATTRIBUTES
{
    DWORD nLength;
    LPVOID lpSecurityDescriptor;
    BOOL bInheritHandle;
}
