// This source code was generated by regenerator
module windowskits.objidl;
import core.sys.windows.unknwn;
import windowskits.guidutil;
import windowskits.winnt;
import core.sys.windows.windef;
import core.sys.windows.basetsd;
import core.sys.windows.winnt;
import windowskits.wtypesbase;
import windowskits.minwindef;
import windowskits.objidlbase;
import windowskits.guiddef;
import core.sys.windows.basetyps;
interface IStorage: IUnknown
{
    static const iidof = parseGUID("0000000b-0000-0000-c000-000000000046");
    HRESULT CreateStream(const(OLECHAR)* pwcsName, DWORD grfMode, DWORD reserved1, DWORD reserved2, IStream* ppstm);
    HRESULT OpenStream(const(OLECHAR)* pwcsName, void* reserved1, DWORD grfMode, DWORD reserved2, IStream* ppstm);
    HRESULT CreateStorage(const(OLECHAR)* pwcsName, DWORD grfMode, DWORD reserved1, DWORD reserved2, IStorage* ppstg);
    HRESULT OpenStorage(const(OLECHAR)* pwcsName, IStorage pstgPriority, DWORD grfMode, SNB snbExclude, DWORD reserved, IStorage* ppstg);
    HRESULT CopyTo(DWORD ciidExclude, const(IID)* rgiidExclude, SNB snbExclude, IStorage pstgDest);
    HRESULT MoveElementTo(const(OLECHAR)* pwcsName, IStorage pstgDest, const(OLECHAR)* pwcsNewName, DWORD grfFlags);
    HRESULT Commit(DWORD grfCommitFlags);
    HRESULT Revert();
    HRESULT EnumElements(DWORD reserved1, void* reserved2, DWORD reserved3, IEnumSTATSTG* ppenum);
    HRESULT DestroyElement(const(OLECHAR)* pwcsName);
    HRESULT RenameElement(const(OLECHAR)* pwcsOldName, const(OLECHAR)* pwcsNewName);
    HRESULT SetElementTimes(const(OLECHAR)* pwcsName, const(FILETIME)* pctime, const(FILETIME)* patime, const(FILETIME)* pmtime);
    HRESULT SetClass(ref IID clsid);
    HRESULT SetStateBits(DWORD grfStateBits, DWORD grfMask);
    HRESULT Stat(STATSTG* pstatstg, DWORD grfStatFlag);
}
alias SNB = LPOLESTR*;
interface IEnumSTATSTG: IUnknown
{
    static const iidof = parseGUID("0000000d-0000-0000-c000-000000000046");
    HRESULT Next(ULONG celt, STATSTG* rgelt, ULONG* pceltFetched);
    HRESULT Skip(ULONG celt);
    HRESULT Reset();
    HRESULT Clone(IEnumSTATSTG* ppenum);
}
