// This source code was generated by regenerator
module windowskits.ocidl;
import core.sys.windows.unknwn;
import windowskits.guidutil;
import windowskits.winnt;
import core.sys.windows.windef;
import core.sys.windows.basetsd;
import core.sys.windows.winnt;
import windowskits.minwindef;
import windowskits.wtypes;
import windowskits.wtypesbase;
import windowskits.guiddef;
import core.sys.windows.basetyps;
import windowskits.oaidl;
interface IPropertyBag2: IUnknown
{
    static const iidof = parseGUID("22f55882-280b-11d0-a8a9-00a0c90c2004");
    HRESULT Read(ULONG cProperties, PROPBAG2* pPropBag, IErrorLog pErrLog, VARIANT* pvarValue, HRESULT* phrError);
    HRESULT Write(ULONG cProperties, PROPBAG2* pPropBag, VARIANT* pvarValue);
    HRESULT CountProperties(ULONG* pcProperties);
    HRESULT GetPropertyInfo(ULONG iProperty, ULONG cProperties, PROPBAG2* pPropBag, ULONG* pcProperties);
    HRESULT LoadObject(LPCOLESTR pstrName, DWORD dwHint, IUnknown pUnkObject, IErrorLog pErrLog);
}
alias PROPBAG2 = tagPROPBAG2;
struct tagPROPBAG2
{
    DWORD dwType;
    VARTYPE vt;
    CLIPFORMAT cfType;
    DWORD dwHint;
    LPOLESTR pstrName;
    CLSID clsid;
}
