// This source code was generated by regenerator
module windowskits.windef;
import core.sys.windows.windef;
import windowskits.winnt;
import core.sys.windows.basetsd;
import core.sys.windows.winnt;
import windowskits.minwindef;
struct HDC__
{
    int unused;
}
struct tagRECT
{
    LONG left;
    LONG top;
    LONG right;
    LONG bottom;
}
struct HMONITOR__
{
    int unused;
}
struct HWND__
{
    int unused;
}
struct tagPOINT
{
    LONG x;
    LONG y;
}
struct tagSIZE
{
    LONG cx;
    LONG cy;
}
struct HBITMAP__
{
    int unused;
}
struct HPALETTE__
{
    int unused;
}
struct HICON__
{
    int unused;
}
