// This source code was generated by regenerator
module windowskits.windef;
import core.sys.windows.windef;
import windowskits.winnt;
import core.sys.windows.winnt;
struct tagRECT
{
    LONG left;
    LONG top;
    LONG right;
    LONG bottom;
}
