// This source code was generated by regenerator
module windowskits.winnt;
import core.sys.windows.windef;
import core.sys.windows.basetsd;
import core.sys.windows.winnt;
import windowskits.minwindef;
struct _LARGE_INTEGER__anonymous_2
{
    DWORD LowPart;
    LONG HighPart;
}
struct _LARGE_INTEGER__anonymous_3
{
    DWORD LowPart;
    LONG HighPart;
}
struct _ULARGE_INTEGER__anonymous_6
{
    DWORD LowPart;
    DWORD HighPart;
}
struct _ULARGE_INTEGER__anonymous_7
{
    DWORD LowPart;
    DWORD HighPart;
}
struct _LARGE_INTEGER
{
    _LARGE_INTEGER__anonymous_2 __param__2;
    _LARGE_INTEGER__anonymous_3 __param__3;
    _LARGE_INTEGER__anonymous_3 u;
    LONGLONG QuadPart;
}
struct _LUID
{
    DWORD LowPart;
    LONG HighPart;
}
struct _ULARGE_INTEGER
{
    _ULARGE_INTEGER__anonymous_6 __param__4;
    _ULARGE_INTEGER__anonymous_7 __param__5;
    _ULARGE_INTEGER__anonymous_7 u;
    ULONGLONG QuadPart;
}
