// This source code was generated by regenerator
module windowskits.wtypes;
import core.sys.windows.winnt;
import windowskits.wtypesbase;
import core.sys.windows.windef;
import windowskits.minwindef;
import windowskits.winnt;
import core.sys.windows.basetsd;
struct tagCY__anonymous_5
{
    ULONG Lo;
    LONG Hi;
}
struct tagDEC___anonymous_15
{
    BYTE scale;
    BYTE sign;
}
struct tagDEC___anonymous_17
{
    ULONG Lo32;
    ULONG Mid32;
}
alias VARTYPE = ushort;
alias VARIANT_BOOL = short;
alias CY = tagCY;
struct tagCY
{
    tagCY__anonymous_5 __param__81;
    LONGLONG int64;
}
alias DATE = double;
alias CLIPDATA = tagCLIPDATA;
struct tagCLIPDATA
{
    ULONG cbSize;
    LONG ulClipFmt;
    BYTE* pClipData;
}
alias BSTR = OLECHAR*;
alias BSTRBLOB = tagBSTRBLOB;
struct tagBSTRBLOB
{
    ULONG cbSize;
    BYTE* pData;
}
alias DECIMAL = tagDEC;
struct tagDEC
{
    USHORT wReserved;
    union {
        tagDEC___anonymous_15 __param__82;
        USHORT signscale;
    }
    ULONG Hi32;
    union {
        tagDEC___anonymous_17 __param__83;
        ULONGLONG Lo64;
    }
}
alias CLIPFORMAT = WORD;
